### ISSUE TITLE
`yarn build` results in type errors

### ISSUE THREAD

**Issue by hayatoevolany** [draftbit/react-native-jigsaw#533]
**Issue:**
Running into an issue with `yarn build`
I did these instructions as it says to in the Readme:
`> git clone https://github.com/draftbit/react-native-jigsaw && cd react-native-jigsaw`
`> yarn && yarn bootstrap && yarn build`

Any ideas on how to fix this issue? It works fine on the iMac I tried it on. Same node version, same process.

Platform Info:
macOS Monterey v12.0.1
MacBook Air (M1, 2020)

Node version: v16.16.0
npm version: 8.18.0

```md
> yarn build

yarn run v1.22.19
$ lerna run prepare
lerna notice cli v5.5.4
lerna info Executing command in 6 packages: "yarn run prepare"
lerna ERR! yarn run prepare exited 1 in '@draftbit/types'
lerna ERR! yarn run prepare stdout:
$ bob build
ℹ Building target commonjs
ℹ Cleaning up previous build at lib/commonjs
ℹ Compiling 5 files in src with babel
✔ Wrote files to lib/commonjs
ℹ Building target module
ℹ Cleaning up previous build at lib/module
ℹ Compiling 5 files in src with babel
✔ Wrote files to lib/module
ℹ Building target typescript
ℹ Cleaning up previous build at lib/typescript
ℹ Generating type definitions with tsc
error TS2688: Cannot find type definition file for 'eslint'.
  The file is in the program because:
    Entry point for implicit type library 'eslint'

error TS2688: Cannot find type definition file for 'estree'.
  The file is in the program because:
    Entry point for implicit type library 'estree'

error TS2688: Cannot find type definition file for 'react-is'.
  The file is in the program because:
    Entry point for implicit type library 'react-is'

error TS2688: Cannot find type definition file for 'resolve'.
  The file is in the program because:
    Entry point for implicit type library 'resolve'


Found 4 errors.

✖ Failed to build definition files.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run prepare stderr:
bob build

build files for publishing

Options:
  --help     Show help                                                 [boolean]
  --version  Show version number                                       [boolean]

Error: Failed to build definition files.
    at build (/Users/evolany53/works/react-native-jigsaw/node_modules/react-native-builder-bob/lib/targets/typescript.js:112:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.handler (/Users/evolany53/works/react-native-jigsaw/node_modules/react-native-builder-bob/lib/index.js:379:9)
error Command failed with exit code 1.
lerna ERR! yarn run prepare exited 1 in '@draftbit/types'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by bluerssen** [comment]
@hayatoevolany Hey! Do you have eslint installed? What version?
